### ISSUE TITLE
Last Execution and Next Execution shows "Invalid Date" after successfull execution of job

### ISSUE THREAD

**Issue by Cnecne59** [bamotav/Hangfire.RecurringJobAdmin#80] opened 2021-02-26 14:20 UTC
Both button show the text "Invalid date", but the recurring job is executed serveral times without any error.
I am using TZ UTC and West european Standard time.
Any ideas what is going wrong?

**Comment by raskajan** [comment] 2021-04-14 07:28
I am able to reproduce your issue when the date format is other than en-us. For example 4/13/2021 2:19 PM works, but 13.4.2021 14:19 not. 

I didn't investigate deeply, but the error will likely be in [JobExtension.html](https://github.com/bamotav/Hangfire.RecurringJobAdmin/blob/326a1aca94e3f99cc4958d187a6c83cb4ee24e9d/src/Hangfire.RecurringJobAdmin/Dashboard/JobExtension.html#38)

**Comment by vipasane** [comment] 2022-02-24 09:46
Quick and dirty fix for datetime format issue this is clearly not the right place since it is an UI issue and should not be sorted out in the backend

File: Hangfire.RecurringJobAdmin\Pages\GetJobDispatcher.cs
`
using Hangfire.Annotations;
using Hangfire.Common;
using Hangfire.RecurringJobAdmin.Core;
using Hangfire.RecurringJobAdmin.Models;
using Hangfire.Storage;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq.Expressions;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace Hangfire.RecurringJobAdmin.Pages
{
    internal sealed class GetJobDispatcher : Dashboard.IDashboardDispatcher
    {
        private readonly IStorageConnection _connection;
        public GetJobDispatcher()
        {
            _connection = JobStorage.Current.GetConnection();
        }
        public async Task Dispatch([NotNull] Dashboard.DashboardContext context)
        {
            if (!"GET".Equals(context.Request.Method, StringComparison.InvariantCultureIgnoreCase))
            {
                context.Response.StatusCode = 405;
                return;
            }

            var recurringJob = _connection.GetRecurringJobs();
            var periodicJob = new List<PeriodicJob>();

            CultureInfo US_TimeFormat = new CultureInfo("en-US");

            if (recurringJob.Count >  0)
            {
                recurringJob.ForEach((x) =>
                {
                    periodicJob.Add(new PeriodicJob
                    {
                        Id = x.Id,
                        Cron = x.Cron,
                        CreatedAt = x.CreatedAt.HasValue ? x.CreatedAt.Value.ChangeTimeZone(x.TimeZoneId) : new DateTime(),
                        Error = x.Error,
                        LastExecution = x.LastExecution.HasValue ? x.LastExecution.Value.ChangeTimeZone(x.TimeZoneId).ToString("G", US_TimeFormat) : "N/A",
                        Method = x.Job?.Method.Name,
                        JobState = "Running",
                        Class = x.Job?.Type.Name,
                        Queue = x.Queue,
                        LastJobId = x.LastJobId,
                        LastJobState = x.LastJobState,
                        NextExecution = x.NextExecution.HasValue ? x.NextExecution.Value.ChangeTimeZone(x.TimeZoneId).ToString("G", US_TimeFormat) : "N/A",
                        Removed = x.Removed,
                        TimeZoneId = x.TimeZoneId
                    });
                });
            }

            //Add job was stopped:
            periodicJob.AddRange(JobAgent.GetAllJobStopped());

            await context.Response.WriteAsync(JsonConvert.SerializeObject(periodicJob));
        }
    }
}

`

**Comment by FixRM** [comment] 2022-12-09 15:42
Hello. Any chance that this will be fixed? BTW, this bug is even visible in Readme.MD of the project

**Comment by bamotav** [comment] 2023-02-13 21:12
Hi guys, I have just accepted the PR that solves this issue, thank you!

**Closed by bamotav** 2023-02-13 21:12 UTC
